# Generated by Django 5.1.1 on 2024-09-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Absorption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, unique=True)),
                ('absorption_rate', models.FloatField(help_text='Pochłanianie CO2 (ton/rok)')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('co2_emission', models.FloatField(help_text='Emisja CO2 na jednostkę (ton)')),
                ('co2_reduction', models.FloatField(default=0.0, help_text='Redukcja CO2 przez alternatywę (ton)')),
                ('alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternatives', to='tools.tool')),
            ],
        ),
    ]
