# Generated by Django 5.1.1 on 2024-09-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='energy_class',
            field=models.CharField(blank=True, help_text='Klasa energetyczna (np. A++, A+)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tools.category'),
            preserve_default=False,
        ),
    ]
