# Generated by Django 5.1.1 on 2024-09-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_category_tool_energy_class_tool_is_electric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='alternative',
        ),
        migrations.AddField(
            model_name='tool',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='alternative_of', to='tools.tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Klasa energetyczna (np. A++, A+)', max_length=4, null=True),
        ),
    ]
