# Generated by Django 5.1.1 on 2024-09-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_tool_alternative_tool_alternatives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='alternatives',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='co2_reduction',
        ),
        migrations.AlterField(
            model_name='tool',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Klasa energetyczna (dotyczy tylko narzędzi elektrycznych)', max_length=4, null=True),
        ),
    ]
