# Generated by Django 5.1.1 on 2024-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_tool_alternatives_remove_tool_co2_reduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='alternative_tools', to='tools.tool'),
        ),
    ]
