# Generated by Django 5.1.1 on 2024-09-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_tool_alternatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='alternatives',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
