# Generated by Django 5.1.1 on 2024-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_remove_tool_alternatives_category_image_tool_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
